Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"
   config.vm.define "namenode" do |namenode|
     namenode.vm.hostname = "namenode"
     namenode.vm.network "private_network", ip: "192.168.31.101"
     namenode.vm.provider "virtualbox" do |vb|
          vb.name = "namenode"
          vb.memory = "1024"
     end
     namenode.vm.provision "file", source: "../script", destination: "."
     namenode.vm.provision "file", source: "../ssh/namenode_rsa", destination: "./namenode_rsa"
     namenode.vm.provision "file", source: "../ssh/namenode_rsa.pub", destination: "./namenode_rsa.pub"
     namenode.vm.provision "shell", path:"install.sh",privileged:false
     namenode.vm.provision "shell",inline:"mv namenode_rsa /home/vagrant/.ssh/id_rsa"
     namenode.vm.provision "shell",inline:"cat namenode_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
  end
  
  config.vm.define "resourcemanager" do |resourcemanager|
     resourcemanager.vm.hostname = "resourcemanager"
     resourcemanager.vm.network "private_network", ip: "192.168.31.102"
     resourcemanager.vm.provider "virtualbox" do |vb|
          vb.name = "resourcemanager"
          vb.memory = "1024"
     end
     resourcemanager.vm.provision "file", source: "../ssh/resourcemanager_rsa", destination: "./resourcemanager_rsa"
     resourcemanager.vm.provision "file", source: "../ssh/resourcemanager_rsa.pub", destination: "./resourcemanager_rsa.pub"
     resourcemanager.vm.provision "file", source: "../ssh/namenode_rsa.pub", destination: "./namenode_rsa.pub"
     resourcemanager.vm.provision "file", source: "../script", destination: "."
     resourcemanager.vm.provision "shell", path:"install.sh",privileged:false
     resourcemanager.vm.provision "shell",inline:"mv resourcemanager_rsa  /home/vagrant/.ssh/id_rsa"
     resourcemanager.vm.provision "shell",inline:"cat namenode_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
     resourcemanager.vm.provision "shell",inline:"cat resourcemanager_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
  end
  config.vm.define "slave1" do |slave1|
     slave1.vm.hostname = "slave1"
     slave1.vm.network "private_network", ip: "192.168.31.103"
     slave1.vm.provider "virtualbox" do |vb|
          vb.name = "slave1"
          vb.memory = "1024"
     end
     slave1.vm.provision "file", source: "../ssh/namenode_rsa.pub", destination: "./namenode_rsa.pub"
     slave1.vm.provision "file", source: "../ssh/resourcemanager_rsa.pub", destination: "./resourcemanager_rsa.pub"
     slave1.vm.provision "file", source: "../script", destination: "."
     slave1.vm.provision "shell",path:"install.sh",privileged:false
     slave1.vm.provision "shell",inline:"cat namenode_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
     slave1.vm.provision "shell",inline:"cat resourcemanager_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
  end
  config.vm.define "slave2" do |slave2|
     slave2.vm.hostname = "slave2"
     slave2.vm.network "private_network", ip: "192.168.31.104"
     slave2.vm.provider "virtualbox" do |vb|
          vb.name = "slave2"
          vb.memory = "1024"
     end
     slave2.vm.provision "file", source: "../ssh/namenode_rsa.pub", destination: "./namenode_rsa.pub"
     slave2.vm.provision "file", source: "../ssh/resourcemanager_rsa.pub", destination: "./resourcemanager_rsa.pub"
     slave2.vm.provision "file", source: "../script", destination: "."
     slave2.vm.provision "shell", path:"install.sh",privileged:false
     slave2.vm.provision "shell",inline:"cat namenode_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
     slave2.vm.provision "shell",inline:"cat resourcemanager_rsa.pub >>/home/vagrant/.ssh/authorized_keys"
  end
 
end
